<?php
$devotee_key = "P12312312";
$devotee_first_name = "Anil";
$devotee_last_name = "Gupta";
$devotee_id_type = "Passport";
$devotee_station = "California";
$accommodation_name = "Gargachal";
$devotee_cell_phone_number="+1 415-622-7879";
$devotee_photo = "";
?>

<!DOCTYPE html>

<html>
<head>
    <title> Card Print </title>
    <style>
        #card{
                background-color: aliceblue;
                border-radius: 3px;
                border-style:double;
                height: 190px;
                width: 320px;   
        
        }
        *{
            font-family: sans-serif;
        
        }
    </style>
</head>

<body>
    <div id="printpage">
        <div id="card">

            
            
            
            <span> <img src="/kdms/assets/img/banner.png"  height="35px" width="310px" style="position:absolute;top:11px;left:14px;"></span>
            <b><center style="position:absolute;top:50px;margin-left:77px;"><?php echo $devotee_first_name . ' ' . $devotee_last_name; ?></center></b>
            <table>
                <tr>
                    <td>
                        <span style="position:absolute;top:80px;left:-50px;margin-left:77px;font-size:13px;"><?php echo '<b> Reg No.</b> ' . $devotee_key; ?></span>
                    </td>
                    <td>
                        <!--<img src="../assets/img/faces/devotee.ico" height="80px" width="60px" >--> 
                    </td>
                </tr>
                <tr><td><span style="position:absolute;top:100px;left:-50px;margin-left:75px;font-size:13px;"><?php echo '<b> Station :</b> ' . $devotee_station; ?></span></td></tr>
                <tr><td><span style="position:absolute;top:120px;left:-50px;margin-left:77px;font-size:13px;"><?php echo ' <b>Id Avail. :</b> ' . $devotee_id_type; ?></span></td></tr>
                <tr><td><span style="position:absolute;top:140px;left:-50px;margin-left:75px;font-size:13px;"><?php echo '<b> Stay at :</b> ' . $accommodation_name; ?></span></td></tr>
                <tr><td><span style="position:absolute;top:160px;left:-50px;margin-left:77px;font-size:13px;"><?php echo '<b> Mobile :</b> ' . $devotee_cell_phone_number; ?></span></td></tr>
                <tr><td><span style="position:absolute;top:180px;left:20px;margin-left:65px;font-size:10px;">This Id is not valid after 15 June 2019</span></td></tr>    
            </table>

            <span style="position:absolute;top:75px;left:250px;">
                <?php
                //if($row1['imageData'] != NULL){            
                //  echo '<img class=\"img-responsive\" style=\"position:absolute;align:right;top:105px;left:25px;width:73px;height:75px;\" src="data:image/jpeg;base64,'.base64_encode( $devotee_photo ).'"/>';
                //}
                //else{
                ?>
                <img src="../assets/    img/faces/devotee.ico" height="80px" width="60px" > 
                <?php
                    // }
                ?>
            </span>



        </div>
    </div>

    <br>
    <a href = "#" onclick="printdiv()"><button >Print </button> </a>

    <script>
        function printdiv(){
            
            var newstr = document.getElementById("printpage").innerHTML;
            var header= '<header><div align="center"><h3 style="color:#EB5005"> Your Header </h3></div><br></header><hr><br>'
            
           // var footer = "Authorized Devotee id Generated By KDMMV2.0"

            var popupWin = window.open('','blank','width=1000,height=700');
            popupWin.document.open();
            popupWin.document.write('<html><body onload="window.print()">'+newstr +'</html></br>');
            popupWin.document.close();
            return false;
            
            }
        
    </script>  
</body>
</html>
