# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iKDMS' do
  use_frameworks!

  # Pods for iKDMS
  pod 'Alamofire', '~> 4.0'

  target 'iKDMSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iKDMSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
